/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WildlifeRouteImport } from './routes/wildlife'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as DiningRouteImport } from './routes/dining'
import { Route as CruiseExperienceRouteImport } from './routes/cruise-experience'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CabinsRouteImport } from './routes/cabins'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CabinsSlugRouteImport } from './routes/cabins.$slug'

const WildlifeRoute = WildlifeRouteImport.update({
  id: '/wildlife',
  path: '/wildlife',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DiningRoute = DiningRouteImport.update({
  id: '/dining',
  path: '/dining',
  getParentRoute: () => rootRouteImport,
} as any)
const CruiseExperienceRoute = CruiseExperienceRouteImport.update({
  id: '/cruise-experience',
  path: '/cruise-experience',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CabinsRoute = CabinsRouteImport.update({
  id: '/cabins',
  path: '/cabins',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CabinsSlugRoute = CabinsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CabinsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking': typeof BookingRoute
  '/cabins': typeof CabinsRouteWithChildren
  '/contact': typeof ContactRoute
  '/cruise-experience': typeof CruiseExperienceRoute
  '/dining': typeof DiningRoute
  '/gallery': typeof GalleryRoute
  '/packages': typeof PackagesRoute
  '/wildlife': typeof WildlifeRoute
  '/cabins/$slug': typeof CabinsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking': typeof BookingRoute
  '/cabins': typeof CabinsRouteWithChildren
  '/contact': typeof ContactRoute
  '/cruise-experience': typeof CruiseExperienceRoute
  '/dining': typeof DiningRoute
  '/gallery': typeof GalleryRoute
  '/packages': typeof PackagesRoute
  '/wildlife': typeof WildlifeRoute
  '/cabins/$slug': typeof CabinsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking': typeof BookingRoute
  '/cabins': typeof CabinsRouteWithChildren
  '/contact': typeof ContactRoute
  '/cruise-experience': typeof CruiseExperienceRoute
  '/dining': typeof DiningRoute
  '/gallery': typeof GalleryRoute
  '/packages': typeof PackagesRoute
  '/wildlife': typeof WildlifeRoute
  '/cabins/$slug': typeof CabinsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/booking'
    | '/cabins'
    | '/contact'
    | '/cruise-experience'
    | '/dining'
    | '/gallery'
    | '/packages'
    | '/wildlife'
    | '/cabins/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/booking'
    | '/cabins'
    | '/contact'
    | '/cruise-experience'
    | '/dining'
    | '/gallery'
    | '/packages'
    | '/wildlife'
    | '/cabins/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/booking'
    | '/cabins'
    | '/contact'
    | '/cruise-experience'
    | '/dining'
    | '/gallery'
    | '/packages'
    | '/wildlife'
    | '/cabins/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookingRoute: typeof BookingRoute
  CabinsRoute: typeof CabinsRouteWithChildren
  ContactRoute: typeof ContactRoute
  CruiseExperienceRoute: typeof CruiseExperienceRoute
  DiningRoute: typeof DiningRoute
  GalleryRoute: typeof GalleryRoute
  PackagesRoute: typeof PackagesRoute
  WildlifeRoute: typeof WildlifeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wildlife': {
      id: '/wildlife'
      path: '/wildlife'
      fullPath: '/wildlife'
      preLoaderRoute: typeof WildlifeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dining': {
      id: '/dining'
      path: '/dining'
      fullPath: '/dining'
      preLoaderRoute: typeof DiningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cruise-experience': {
      id: '/cruise-experience'
      path: '/cruise-experience'
      fullPath: '/cruise-experience'
      preLoaderRoute: typeof CruiseExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabins': {
      id: '/cabins'
      path: '/cabins'
      fullPath: '/cabins'
      preLoaderRoute: typeof CabinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabins/$slug': {
      id: '/cabins/$slug'
      path: '/$slug'
      fullPath: '/cabins/$slug'
      preLoaderRoute: typeof CabinsSlugRouteImport
      parentRoute: typeof CabinsRoute
    }
  }
}

interface CabinsRouteChildren {
  CabinsSlugRoute: typeof CabinsSlugRoute
}

const CabinsRouteChildren: CabinsRouteChildren = {
  CabinsSlugRoute: CabinsSlugRoute,
}

const CabinsRouteWithChildren =
  CabinsRoute._addFileChildren(CabinsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookingRoute: BookingRoute,
  CabinsRoute: CabinsRouteWithChildren,
  ContactRoute: ContactRoute,
  CruiseExperienceRoute: CruiseExperienceRoute,
  DiningRoute: DiningRoute,
  GalleryRoute: GalleryRoute,
  PackagesRoute: PackagesRoute,
  WildlifeRoute: WildlifeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
